{
 "title": "Health Checks",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Stateful Set Health Checks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{} / kube_statefulset_status_replicas{}",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "Stateful Set Health Checks",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "kube_statefulset_status_replicas_ready{} / kube_statefulset_status_replicas{}",
     "legendFormat": "{{statefulset}}"
    }
   ]
  },
  {
   "title": "Deployment Health Checks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{} / kube_deployment_status_replicas{}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Deployment Health Checks",
   "type": "state-timeline",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{} / kube_deployment_status_replicas{}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Daemonset Health Checks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "kube_daemonset_status_current_number_scheduled{} / kube_daemonset_status_desired_number_scheduled{}",
     "legendFormat": "{{daemonset}}"
    }
   ]
  }
 ]
}