{
 "title": "K8s Node Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "nodeNumber",
    "query": {
     "query": "node_memory_SwapTotal_bytes{job=\"k8s_node\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"k8s_node\"} - node_memory_MemAvailable_bytes{job=\"k8s_node\"}) / node_memory_MemTotal_bytes{job=\"k8s_node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$nodeNumber",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "repeat": "nodeNumber",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"k8s_node\",instance=\"192.168.1.1$${nodeNumber}:9100\"} - node_memory_MemAvailable_bytes{job=\"k8s_node\"}) / node_memory_MemTotal_bytes{job=\"k8s_node\"}",
     "legendFormat": "{{nodeNumber}}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"k8s_node\"} - node_memory_SwapFree_bytes{job=\"k8s_node\"}) / node_memory_SwapTotal_bytes{job=\"k8s_node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$nodeNumber",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 21 },
   "repeat": "nodeNumber",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"k8s_node\",instance=\"192.168.1.1$${nodeNumber}:9100\"} - node_memory_SwapFree_bytes{job=\"k8s_node\"}) / node_memory_SwapTotal_bytes{job=\"k8s_node\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (1 - rate(node_cpu_seconds_total{job=\"k8s_node\",mode=\"idle\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg by (instance) (node_thermal_zone_temp{job=\"k8s_node\",zone=\"0\"})*9/5)+32",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}