{
 "title": "Magic Smoke",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "IO/Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ethernet I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(ifOutOctets{instance!=\"192.168.1.1\"}[$__rate_interval])) * -8",
     "legendFormat": "{{instance}} out"
    },
    {
     "expr": "sum by (instance) (rate(ifInOctets{ifName=~\"eth.*\", instance!=\"192.168.1.1\"}[$__rate_interval])) * 8",
     "legendFormat": "{{instance}} in"
    }
   ]
  },
  {
   "title": "Router I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(ifOutOctets{instance=\"192.168.1.1\"}[$__rate_interval])) * -8",
     "legendFormat": "{{instance}} out"
    },
    {
     "expr": "sum by (instance) (rate(ifInOctets{instance=\"192.168.1.1\"}[$__rate_interval])) * 8",
     "legendFormat": "{{instance}} in"
    }
   ]
  },
  {
   "title": "External Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"http_ping\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Local DNS Resolution Success",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "probe_success{job=\"local_dns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Remote DNS Resolution Latency",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "probe_success{job=\"remote_dns\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Local DNS Resolution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_dns_duration_seconds{job=\"local_dns\"}) by (instance)",
     "legendFormat": "{{instance}}: {{phase}}"
    }
   ]
  },
  {
   "title": "Remote DNS Resolution Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_dns_duration_seconds{job=\"local_dns\"}) by (instance)",
     "legendFormat": "{{instance}}: {{phase}}"
    }
   ]
  }
 ]
}