{
 "title": "Synology Nginx Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Query Access from non-local",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (client) (count_over_time({filename=\"/var/log/nginx/access.log\"} != ip(\"192.168.1.1/16\") != ip(\"127.0.0.1\") != \"SYSTEM\" | pattern `<client> - <_> <_> \"<request>\" <code> <size> \"-\" \"<user_agent>\" \"-\"`[5m]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Nginx Outside queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (client) (count_over_time({filename=\"/var/log/nginx/access.log\"} != ip(\"192.168.1.1/16\") != ip(\"127.0.0.1\") != \"SYSTEM\" | pattern `<client> - <_> <_> \"<request>\" <code> <size> \"-\" \"<user_agent>\" \"-\"`[$__interval]))",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Non-Local Nginx Queries",
   "type": "logs",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/nginx/access.log\"} != ip(\"192.168.1.1/16\") != ip(\"127.0.0.1\") != ip(\"172.0.0.0/16\") != \"SYSTEM\" | pattern `<source_ip> - - <_> \"<method> <url> <_>\" <status> <_> <_> \"<_>\" <_>` "
    }
   ]
  },
  {
   "title": "Non-local Useragents",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by (useragent) (count_over_time({filename=\"/var/log/nginx/access.log\"} != ip(\"192.168.1.1/16\") != ip(\"127.0.0.1\") != ip(\"172.0.0.0/16\") != \"SYSTEM\" | pattern `<source_ip> - - <_> \"<method> <url> <_>\" <status> <bytes> <_> \"<useragent>\" <_>`[5m]))",
     "legendFormat": "{{client}}"
    }
   ]
  }
 ]
}